# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e94829d14b759340a0ad8e36ead994e6cb7ccd0d8881e2cc420a97d5564e37586f38a852d7c46c740043a03d34fd55a678a8f4cb9302f68d5f0bbc47e0acaf20

test:
  secret_key_base: bbea040ea1a252e349242a04cd7ee6f2b4a34c87767bf3f1bf5de97b57cc8be78820ef9b5545ee36e55a0d6f11723063c4b6f40d368d72ed4a5a897699ef82bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
